# Generated by Django 6.0.7 on 2026-07-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Peticiones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nroPeticion", models.IntegerField()),
                ("metodo", models.CharField(max_length=255)),
                ("dominio", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("https", models.BooleanField()),
                ("peticion", models.CharField()),
                ("respuesta", models.CharField()),
            ],
        ),
    ]
