# Generated by Django 6.0.7 on 2026-07-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="peticiones",
            name="codigo_respuesta",
            field=models.CharField(default=""),
        ),
        migrations.AlterField(
            model_name="peticiones",
            name="respuesta",
            field=models.CharField(default=""),
        ),
    ]
